Testpermillion
covid19india/covid19india.github.io pull request #1028
Opened 2020-04-13 05:37 UTC by kp666

**Description of PR**

**Type of PR**

- [ ] Bugfix
- [* ] New feature

**Relevant Issues**  
Fixes #...

**Checklist**

- [* ] Compiles and passes lint tests
- [ ] Properly formatted
- [* ] Tested on desktop
- [ ] Tested on phone

**Screenshots**
![image](https://user-images.githubusercontent.com/165359/79095023-e46a3500-7d76-11ea-8335-c157f36169a8.png)

2020-04-13 07:43 UTC, tannakartikey commented
@kp666 this PR is related to which issue can you please mention?

2020-04-13 07:51 UTC, kp666 commented
@tannakartikey  its a feature. I haven't put an issue

2020-04-13 08:37 UTC, kp666 commented
Added Issue #1028

2020-04-13 11:54 UTC, tannakartikey requested changes
@kp666 we will accept and review the PR in detail if the issue is accepted.
Follow the contribution guide for more details:
https://github.com/covid19india/covid19india-react/blob/master/CONTRIBUTING.md

Until then I have reviewed the PR at a glance.

2020-04-13 11:54 UTC, tannakartikey commented on src/components/home.js
> +  const million = 1000000;
can you convert it to `const MILLION = 1000000`?

2020-04-13 11:54 UTC, tannakartikey commented on src/components/data/state_wise_population_2011.json
> +{
Can you comment in the file with the source of this data?

2020-04-13 15:42 UTC, kp666 commented on src/components/data/state_wise_population_2011.json
> +{
Could you propose how to comment on a json file?

2020-04-15 06:45 UTC, kp666 commented on src/components/data/state_wise_population_2011.json
> +{
The source of the data is district wise 2011 census data available here: https://www.kaggle.com/danofer/india-census
except andhra pradesh and telegana.
For Andhra Pradesh and Telegana I used data available on wikipedia.

2020-04-16 18:00 UTC, jeremyphilemon requested changes
Hey @kp666, this looks good! However, we don't want to show this data upfront on the table. We'd like to show it on the state page like this right below the `meta-secondary` component. Have it labelled as "Tests per million" rather than what I've put there: 

<img width="170" alt="Screen Shot 2020-04-16 at 8 59 58 PM" src="https://user-images.githubusercontent.com/17938322/79490265-44860300-8025-11ea-82c3-ef894595ad73.png">

Let me know if you can make those changes :)

2020-04-18 02:22 UTC, kp666 commented
@jeremyphilemon The intention from my side is not just to show data, but pressure states into rigorous testing. I feel the right place for that is upfront on the table, rather than hide it inside state page.

2020-04-18 02:31 UTC, jeremyphilemon commented
I understand your sentiment, but it's not logistically possible to show all data in one place, which in this case is the table.

Furthermore, it is also counterintuitive to your cause because at the end of the day you're still just showing data, I fail to see how placing this in the table would "pressurize" the authorities into doing things than if it were placed elsewhere. 

Let me know what you think.

2020-04-18 02:34 UTC, kp666 commented
It is easier to compare states that do rigorous testing when data is listed on a list, rather than on the state page.  A sorted list like the one attached makes more sense to viewers than stats in a state page. 
Also Its always possible to change layout when you want to show more data. 

![image](https://user-images.githubusercontent.com/165359/79626109-2fa38f80-814b-11ea-873b-7434d549e4b5.png)

2020-06-07 13:46 UTC, jeremyphilemon commented
Hey thanks for the PR! You can view "tests per million" on the individual state pages. Feel free to open PRs against available issues :)

2020-06-07 13:46 UTC, closed without merging