fixed scrolling of pages when navbar is open
covid19india/covid19india.github.io pull request #1184
Opened 2020-04-16 17:00 UTC by Binu42

**Description of PR**
fixed scrolling of pages when navbar is opened.

**Type of PR**

- [x] Bugfix

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

2020-04-17 09:11 UTC, jeremyphilemon requested changes
Hey it looks like this has caused misalignment in the navbar on mobiles, and I'm still able to scroll down from the expanded navbar? (I tried this on my laptop with responsive mode on maybe I should try this on the phone to work?)

<img width="493" alt="Screen Shot 2020-04-17 at 12 09 40 PM" src="https://user-images.githubusercontent.com/17938322/79552960-725e5c80-80a4-11ea-94a1-f85174a481e3.png">

Otherwise we're good, can you look into what may be the problem?

2020-04-17 09:11 UTC, jeremyphilemon commented on src/components/navbar.js
> +    if (expand) document.body.classList.add('modal-open');
Hey thanks! Can you make the classes self-documenting as well, like "scroll-disabled" or something like that, which would also support the current modals?

2020-04-17 09:33 UTC, Binu42 commented on src/components/navbar.js
> +    if (expand) document.body.classList.add('modal-open');
okay for sure...

2020-04-17 10:16 UTC, Binu42 commented
> Hey it looks like this has caused misalignment in the navbar on mobiles, and I'm still able to scroll down from the expanded navbar? (I tried this on my laptop with responsive mode on maybe I should try this on the phone to work?)
> 
> <img alt="Screen Shot 2020-04-17 at 12 09 40 PM" width="493" src="https://user-images.githubusercontent.com/17938322/79552960-725e5c80-80a4-11ea-94a1-f85174a481e3.png">
> 
> Otherwise we're good, can you look into what may be the problem?

@jeremyphilemon thanks for your review i have changed the things accordingly. and i'm not able to see any misalignment in navbar on mobiles and i'm not able to scroll when navbar is open please check it once the recent link for now is https://covid19india-react-df2amcylo.now.sh

2020-04-17 16:05 UTC, Binu42 commented
@jeremyphilemon i noticed misalignment in navbar little late it's fixed now, thanks.

2020-04-17 23:18 UTC, jeremyphilemon requested changes
Looks good.

Some issues I still found:
- The home screen seems to be jumping when the navbar is toggled on desktop
- Let's not have the backdrop bg as blue
- If you're highlighting the options like this:
<img width="264" alt="Screen Shot 2020-04-18 at 2 17 14 AM" src="https://user-images.githubusercontent.com/17938322/79621078-bbe98e80-811a-11ea-8ac7-75a00d952fe8.png">
  it'd be better if you could also have the font change it's color to $pblue.


Also squash your commits and rebase, please :)

2020-04-18 15:37 UTC, Binu42 commented
@jeremyphilemon i have changed backdrop bg to transparent dark and active page navbar color to $blue also taken care of jumping on pages. have a look on recent deployment.

2020-04-18 18:56 UTC, jeremyphilemon commented
@Binu42 Hey thanks for the quick turnaround!

It still seems to jump around for me on safari (macOS) :/ Could you try preserving this design instead, it doesn't have to be filled even of the left – it was left like that intentionally. 

<img width="153" alt="Screen Shot 2020-04-18 at 9 55 50 PM" src="https://user-images.githubusercontent.com/17938322/79668713-6d420000-81bf-11ea-8c7c-42f980086f6c.png">

Thanks :)

2020-04-18 19:13 UTC, Binu42 commented
@jeremyphilemon i've unchange my last commits related with nav-right btn (menu & close).

2020-04-20 00:26 UTC, Binu42 commented
@jeremyphilemon can u look for this also and give some feedback.

2020-04-21 22:38 UTC, jeremyphilemon commented
Patched by #1364

2020-04-21 22:38 UTC, closed without merging