Fixed - Hover out of State table issue
covid19india/covid19india.github.io pull request #1264
Opened 2020-04-18 18:25 UTC by dipali2098

**Description of PR**
While hovering out of the State table, now shows overall map instead of previously hovered state.
**Type of PR**

- [-] Bugfix
- [ ] New feature

**Relevant Issues**  
Fixes #...

**Checklist**

- [-] Compiles and passes lint tests
- [-] Properly formatted
- [-] Tested on desktop
- [-] Tested on phone

**Screenshots**

2020-04-18 20:02 UTC, vishwac09 requested changes
Check some comments

2020-04-18 20:02 UTC, vishwac09 commented on src/components/mapexplorer.js
> +          setCurrentHoveredRegion(region);
avoid duplicate function calls. **setCurrentHoveredRegion**, **setPanelRegion**, **onMapHighlightChange** are being referred twice with just a change in param region and noregion.
Write them once and manipulate the value passed to them as.
`
let region ;
if (!region){
   region = noregion;
}
setCurrentHoveredRegion(region);
setPanelRegion(region);
onMapHighlightChange(region)
`

2020-04-18 20:02 UTC, vishwac09 commented on src/components/home.js
> +// const getRegionFromState = (state) => {
remove commented

2020-04-22 12:22 UTC, jeremyphilemon commented
Hey, thanks for the PR! 

Please raise PRs against issues you've been assigned to and have them referenced in the PR :)

2020-04-22 12:22 UTC, closed without merging