Adding scroll to top button (w/ animation) to all pages
covid19india/covid19india.github.io pull request #1315
Opened 2020-04-19 20:18 UTC by aswaathb

**Description of PR**
- Scroll Buttons for Home, Demographics and State pages<sup>1</sup>
- Uses Feather Icons (w/ color palette from App.scss)
- Animated Scroll
- Scroll Button only appears when user has scrolled down the page

<sup>1</sup>Button is implemented for the Essentials page too but that'll feature in a later release

**Type of PR**

- [x] Bugfix
- [ ] New feature

**Relevant Issues**  
Fixes issue #1273 
Note: Saw PR #1274 already solves the issue but I preempted more issues being raised for the other pages. Also the animation fits in well

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [ ] Tested on phone

**Screenshots**
_Home_
![scroll_home](https://user-images.githubusercontent.com/25769767/79698642-4bb64680-829b-11ea-8546-2730e55128d5.gif)

_Patients DB_
![scroll_patients](https://user-images.githubusercontent.com/25769767/79698629-3e995780-829b-11ea-884c-6e89d10befd0.gif)

_State (eg. MH)_
![scroll_state](https://user-images.githubusercontent.com/25769767/79698625-36411c80-829b-11ea-8d32-2ac0425195ce.gif)

2020-04-20 15:56 UTC, vishwac09 requested changes

2020-04-20 15:56 UTC, vishwac09 commented on src/components/patientdb.js
> +    window.pageYOffset > 100 ? setHasScrolled(true) : setHasScrolled(false);
move 100 to src/constants.js then reference here

2020-04-20 15:56 UTC, vishwac09 commented on src/components/patientdb.js
> +    window.pageYOffset > 100 ? setHasScrolled(true) : setHasScrolled(false);
same here !

2020-04-20 15:56 UTC, vishwac09 commented on src/components/state.js
> +    window.pageYOffset > 100 ? setHasScrolled(true) : setHasScrolled(false);
move 100 to src/constants.js then reference here

2020-04-20 15:56 UTC, vishwac09 commented on src/components/state.js
> +    window.pageYOffset > 100 ? setHasScrolled(true) : setHasScrolled(false);
same here !

2020-04-20 15:56 UTC, vishwac09 commented on src/components/state.js
> +                position: 'fixed',
move style to App.scss, ref using className

2020-04-22 12:14 UTC, jeremyphilemon commented
Hey, thanks for the PR! Would like a discussion and an approval in the issue referenced before moving forward with a PR.

2020-04-22 12:14 UTC, closed without merging