Fix: Rendering unnecessary district table rows
covid19india/covid19india.github.io pull request #1429
Opened 2020-04-22 22:43 UTC by abhishekakade

**Description of PR**
- Fixes the unnecessary district information being rendered on initial page load. Table will now render only the states information and will render districts information only when user clicks or taps on the state name/s.
- The number of DOM elements rendered on initial page load went down from 4800 to less than 1500.
- Will help reduce render time and main thread work load and overall performance.

**Type of PR**
- [x] Bugfix

**Relevant Issues**  
Closes #1428

**Checklist**
- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [ ] Tested on phone

2020-04-22 22:59 UTC, abhishekakade commented
Looks like tests will need an update.

2020-04-23 00:50 UTC, jeremyphilemon commented
cc @tannakartikey how do we go about the test cases? I see this as a win for cutting down the number of renders.

2020-04-23 04:15 UTC, tannakartikey commented
@jeremyphilemon I updated my specs. Please review it on the link mentioned. Once it's merged this PR will also be updated.

@abhishekakade you need to merge my PR towards your repo.

https://github.com/abhishekakade/covid19india-react/pull/1

2020-04-23 04:20 UTC, tannakartikey requested changes
Need to merge abhishekakade#1 before the merge!

2020-04-23 08:28 UTC, tannakartikey approved these changes
LGTM

2020-04-23 08:32 UTC, abhishekakade commented
@tannakartikey, @jeremyphilemon, merged the testing PR. @tannakartikey, thank you!

2020-04-23 09:34 UTC, jeremyphilemon commented
Thanks @abhishekakade and @tannakartikey for the PR! :D

2020-04-23 09:35 UTC, merged