Tooltip for districts table
covid19india/covid19india.github.io pull request #1476
Opened 2020-04-24 03:35 UTC by Abhinav-Mani

**Description of PR**
Support notes as Tooltips for district rows

**Relevant Issues**  
Fixes #1472 

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**

At the time of pull request all district note were empty. If it receive a note it will look like this

![primg](https://user-images.githubusercontent.com/47060625/80172336-5e69ac00-860a-11ea-9235-a7f148722dd9.jpg)

2020-04-24 14:06 UTC, jeremyphilemon requested changes
Hey, so it looks like you're rendering a react tooltip component for every row, let's not do that. I believe you can just render it once in the table component with `id="unknown"` and the tooltip will work for all instances of elements that have `data-for="unknown"`.

Also we added notes in the backend, but it looks like some of them are not working (check Italians under Haryana)

Otherwise looks good :)

2020-04-24 18:33 UTC, nayakrahul commented
Hey @Abhinav-Mani , it removed the tooltip from unknown in district sub-table. Since unknown doesn't have a note in it, the tooltip icon is not rendered. A default tooltip note was present for unknown ones.

2020-04-24 18:41 UTC, Abhinav-Mani commented
@nayakrahul I didn't knew that.

2020-04-25 00:23 UTC, jeremyphilemon approved these changes

2020-04-25 00:26 UTC, merged