Feat: highlight the currently selected row in table
covid19india/covid19india.github.io pull request #1482
Opened 2020-04-24 07:55 UTC by nayakrahul

**Description of PR**
This PR highlights the currently selected row in table on change in map and timeseries charts. It has the same style as it is when hover.

**Relevant Issues**  
Fixes #1473

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [] Tested on phone

**Screenshots**

2020-04-24 08:12 UTC, shuklaayush commented
Nice! Can you add support for the district rows as well?

2020-04-24 09:38 UTC, akashverma reviewed
nice work!

2020-04-24 11:37 UTC, shuklaayush commented on src/components/table.js
> +                        : false
This is not required, right?

2020-04-24 11:46 UTC, nayakrahul commented on src/components/table.js
> +                        : false
Oh yeah

2020-04-24 12:17 UTC, shuklaayush commented on src/components/table.js
> +  return false;
Might be better to compare the props to check if they're unchanged instead of always returning false. Otherwise, it would lead to extra renders.

2020-04-24 15:03 UTC, jeremyphilemon requested changes
This looks good!

Rather than setting the state, can we pass the prop instead and check in order to limit the re-renders that occur? Essentially we would want a re-render to fire only for the said selected row if it's highlighted state (as a prop) changes.

2020-04-24 15:13 UTC, nayakrahul commented
If the Table component receives the same props as previous one, then the component will not be re-rendered. I am writing the comparison function for it as told by @shuklaayush .

2020-04-24 15:28 UTC, jeremyphilemon commented
@nayakrahul yes you're right, I missed that. 

I was gonna say instead of adding a new state variable in home to track the row highlighted, you can use `activeState` and `regionHighlighted` (for districts) instead.

2020-04-24 15:33 UTC, nayakrahul commented
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/11428805/80229985-e08bbc00-866e-11ea-809f-6856a17b6090.gif)
I printed a statement to the console when table component re-renders. You can see that the statement gets printed only when hovered state is changed in map.

2020-04-25 00:30 UTC, jeremyphilemon approved these changes

2020-04-25 00:31 UTC, jeremyphilemon commented
Well I was clearly wrong about the re-renders, but I was trying to make the case that a duplicate variable to track the highlighted need to be made because we're already tracking that in activeState and regionHighlighted. 

However, I'll take this anyway. Thanks :)

2020-04-25 00:38 UTC, merged